### ISSUE TITLE
Use DI instead of instantiating object manually

### ISSUE THREAD

**Issue by Ch4mpl00** [alijumaan/Laravel-Ecommerce#11]
https://github.com/alijumaan/Laravel-Ecommerce/blob/4b88d4b63f121e0dc837a8518f39df93f86d22d1/app/Http/Controllers/Backend/ProductController.php#L87

When the ProductService requires some dependencies like repository or any other service class then you have to add this dependencies manually to any place where you had instantiated the ProductService.
What you should do is just inject ProductService to constructor

```
class ProductController ...
{
     /** @var ProductService */
     private $productService;

    public function __construct(ProductService $productService)
    {
         $this->productService = $productService;
    }
}
```

and Laravel's IoC container will instantiate it with all it's dependencies for you

**Comment by alijumaan** [comment]
Thank you
