### ISSUE TITLE
Don't use abort / abort_if functions outside http layer

### ISSUE THREAD

**Issue by Ch4mpl00** [alijumaan/Laravel-Ecommerce#13]
https://github.com/alijumaan/Laravel-Ecommerce/blob/4b88d4b63f121e0dc837a8518f39df93f86d22d1/app/Repositories/Backend/CategoryRepository.php#L33

Here you call abort_if from a repository but it is not a repository responsibility to abort request.
Repository might throw an exceptions but not http related.

Also checking if user is allowed to do something is also not a repository responsibility.

**Comment by alijumaan** [comment]
You are right, I will move all "if statement" to the controller or any PHP class like service or job.
