### ISSUE TITLE
Unnecessary permision errorr

### ISSUE THREAD

**Issue by Ajibolarilwan14** [alijumaan/Laravel-Ecommerce#14]
The line should be wrap in a condition like @can and @endcan so it automatically hides the create link and doesn't throw permission error when someone logged in as a supervisor.

https://github.com/alijumaan/Laravel-Ecommerce/blob/46c58cd2b65f65046bdbb58a30c969350bd0f911/resources/views/backend/layouts/sidebar.blade.php#L70

**Comment by alijumaan** [comment]
Thanks, I forget to add @can into the blade.
