### ISSUE TITLE
Setting Request object to repository methods

### ISSUE THREAD

**Issue by ivandowhai** [alijumaan/Laravel-Ecommerce#15]
https://github.com/alijumaan/Laravel-Ecommerce/blob/42abb71ca559e8b06aad4c76a2fd22a13ed5bd84/app/Http/Controllers/Backend/ReviewController.php#L42
I see that you set $request to the repository method, but it's a violation of the principle of single responsibility. Your repository shouldn't know anything about UpdateReviewRequest class, it should take only data as array.
For example:
In controller: 
```
    public function update(UpdateReviewRequest $request, Review $review)
    {
        $this->reviewRepository->update($request->only(['name', 'email', 'status', 'review']), $review);

        return redirect()->route('admin.reviews.index')->with(['message' => 'Review updated successfully', 'alert-type' => 'success']);
    }
```

in repository:
```
    public function update(array $request, Review $review)
    {
        $review->update($request);

        clear_cache();
   }
```

**Comment by alijumaan** [comment]
Very helpful.
