### ISSUE TITLE
not enough validation rules 

### ISSUE THREAD

**Issue by Abdo-Najjar** [alijumaan/Laravel-Ecommerce#17]
https://github.com/alijumaan/Laravel-Ecommerce/blob/1642973504055d79ca60076f13e64b89560eda15/app/Http/Requests/UpdateReviewRequest.php#L27

if you are using a required validation rule only on a string field in the migration it may cause an error if the user enter an input more
than 255 character length you need to make sure to use max:255 beside the required rule in the request.

**Comment by alijumaan** [comment]
Sure.
Thank you
