### ISSUE TITLE
Using middleware

### ISSUE THREAD

**Issue by Null78** [alijumaan/laravel-ecommerce#18]
i see you have used `abort_if(!auth()->user()->can(''), 403, '');` so many times in the controllers,
but you could easily manage the permissions by using a middleware since you already have a `role` table and `role_id` column on the `users` table.

so here is the link to the docs https://laravel.com/docs/8.x/middleware
also a video with a few tips from Laravel Daily on how to write a better middleware https://youtu.be/sukS7QOBpK0?t=248  

.

https://github.com/alijumaan/Laravel-Ecommerce/blob/1642973504055d79ca60076f13e64b89560eda15/app/Http/Controllers/Backend/UserController.php#L29
https://github.com/alijumaan/Laravel-Ecommerce/blob/1642973504055d79ca60076f13e64b89560eda15/app/Http/Controllers/Backend/UserController.php#L48
https://github.com/alijumaan/Laravel-Ecommerce/blob/1642973504055d79ca60076f13e64b89560eda15/app/Http/Controllers/Backend/CategoryController.php#L25
https://github.com/alijumaan/Laravel-Ecommerce/blob/1642973504055d79ca60076f13e64b89560eda15/app/Http/Controllers/Backend/PageController.php#L33

**Comment by alijumaan** [comment]
You right, I will do that

**Comment by alijumaan** [comment]
I agree for your suggestion about doing a short way and avoid duplicated codes, but I think in this case each function has specific permission, for example, Create Function only when the user has permission to create ...

**Comment by Muneebkh2** [comment]
@alijumaan if we strict routes on role based via **middleware**, so I think we didn't;t need to use this in each function.
