### ISSUE TITLE
Can optimize

### ISSUE THREAD

**Issue by sulavalentin** [alijumaan/laravel-ecommerce#20]
https://github.com/alijumaan/Laravel-Ecommerce/blob/e4c4ec68a5339ffbc3f24af769ca7056e9ff0a32/app/Models/Product.php#L94

can use this

> **return $this->ratings()->exists() ? $this->ratings()->sum('value') / $this->ratings()->count() : 0;**

or this

> **$ratingCount =  $this->ratings()->count();
> return $ratingCount ? $this->ratings()->sum('value') / $ratingCount : 0;**

**Comment by alijumaan** [comment]
if the result same choose what you prefer
in fact, I remember this line it takes me more time to work
