### ISSUE TITLE
Hard coded secret in code

### ISSUE THREAD

**Issue by skrskr** [alijumaan/laravel-ecommerce#25]
https://github.com/alijumaan/laravel-ecommerce/blob/f098bb546989195c8918ec801ed0eee85e7284dc/app/Services/TapService.php#L23

you need to add api_key and base url to .env file and create config file for example tap.php.
if base url and api key changed from testing to production it's easy to change it on .env file only not every where on code.

**Comment by alijumaan** [comment]
Thank you Mohamed 👍
