### ISSUE TITLE
Having issues adding additional fields to the product table

### ISSUE THREAD

**Issue by ojiezele123** [alijumaan/laravel-ecommerce#27]
![0298C616-9150-4321-B82F-6D96929D626F](https://user-images.githubusercontent.com/28743550/157000773-12c4cd3f-22d7-4593-8527-f481a8b712f3.png)

I have modified the product table and added a new field,(user id) but I can't modify the Product:: create function to add this field to the database, any solution??

**Comment by alijumaan** [comment]
add user id to ProductRequest array

**Comment by ojiezele123** [comment]
Thanks bro

**Comment by ojiezele123** [comment]
How do I add more details to order table and update it from controller?
