### ISSUE TITLE
Refactor for can't re-used code.

### ISSUE THREAD

**Issue by Muneebkh2** [alijumaan/Laravel-Ecommerce#3]
https://github.com/alijumaan/Laravel-Ecommerce/blob/0fd727565de50cd3063262d7738a53a2f539cc8a/app/Repositories/Frontend/ProductRepository.php#L71

you just need to save auth user id in var to reuse in method. you also use this in line 76.
`AuthUserId = auth()->user()->id`

**Comment by Loafer19** [comment]
also you can use relation like this
`auth()->user()->ratings()->where('product_id', $product->id)->first()`
or add a scope for getting one project from relation
