### ISSUE TITLE
Maybe you can you call the blade instead of controller here

### ISSUE THREAD

**Issue by damnlord** [alijumaan/Laravel-Ecommerce#5]
https://github.com/alijumaan/Laravel-Ecommerce/blob/a09cff34ce8597fe71c5f6c9f6957d28e1f0950e/routes/admin.php#L28

You have a controller just to return a view

class AdminController extends Controller
{
    public function index()
    {
        return view('backend.index');
    }
}
Maybe will be better if you call the view in the routed directly. This way you will have one less controller to load.

**Comment by alijumaan** [comment]
of course in this case call the view in the routed directly
Thanks for the review.
