### ISSUE TITLE
You may want to use when instead of if

### ISSUE THREAD

**Issue by damnlord** [alijumaan/laravel-ecommerce#8]
https://github.com/alijumaan/Laravel-Ecommerce/blob/4b88d4b63f121e0dc837a8518f39df93f86d22d1/app/Traits/FilterTrait.php#L19
You have a lot "if not null checks" here while you build your query, instead you can you use when
$var = $query;
  if ($keyword != null) {
            $var = $var->search($keyword);
        }
______________________
$var = $query
->when($keyword, fn ($query, $value) =>$query->search($keyword) )
->when($somevar, fn ($query, $value) =>$query->where/whereHas .....whereProductId ..... (whatever you need)($keyword) )

for more information you can check here https://laravel.com/docs/8.x/queries#conditional-clauses

be advised that this syntax will work with php 7.4+
for php less than 7.4 
->when($xxxx, function ($query, $yyyy) {
                    return $query->where('col', $yyyy);
                })

**Comment by alijumaan** [comment]
I build a global class for every controller need filter so I reuse it.
and can you give more examples to make these shorter, please?

Php version 7.4.16

**Comment by damnlord** [comment]
You check you variables if they are not null before you use them in a query (which is fine), bu you can make it shorter
"The when method only executes the given closure when the first argument is true."
you code looks like this : 
$var = $query;
        if ($categoryId != null) {
            $var = $var->whereCategoryId($categoryId);
        }
        if ($productId != null) {
            $var = $var->whereProductId($productId);
        }
instead it can look like this:
$var = $query
->when($categoryId, fn ($query, $value) =>$query->whereCategoryId($value) )
->when($productId, fn ($query, $value) =>$query->whereProductId($value) );

In the call back function you can you use whatever you want like whereHas or wher or micro .... it's up to you and your logic.

you don't even need to make isset checks


you trait function should look like this

    public function filter($query)
    {

        $var = $query
	->when(request()->keyword, fn ($query, $value) =>$query->search($value))
	->when(request()->status, fn ($query, $value) =>$query->whereStatus($value))
	->when(request()->categoryId, fn ($query, $value) =>$query->whereCategoryId($value))
	->when(request()->tagId, fn ($query, $value) =>$query->whereHas('tags', function ($query) use ($value) {
                $query->where('id', $value);
            }))
	->when(request()->productId, fn ($query, $value) =>$query->whereProductId($value))
	->orderBy($sortBy, $orderBy);
        ->paginate($limitBy);

        return $var;
}

The WHEN method will do all the checks for you and it will triger the call back only when the variable is there and not null ;)
